### ISSUE TITLE
09/30/2019 Staging Deployment

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-deploy#1195]
Please update code on staging.cnx.org. Refer to DevOps tasks checklist below.

Link to Release Milestone:
https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/reports/burndown?milestoneId=4651393&selectedPipelines=5cdc86db0f84751dcd8fd93a

Repos updated:
- [ ] cnx-recipes 1.39.0

Notes to DevOps:
cnx-deploy will need to be revved as usual.

**Comment by DarkPrinceFrost** [comment]
Current tag `v3.1.1`

**Comment by DarkPrinceFrost** [comment]
`v3.1.2` deployed
