### ISSUE TITLE
CE 10/23/2019 Production Deployment

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-deploy#1208]
Deploy: 
- [x] cnx-deploy v3.1.5

### Release to Production
- [ ] CE uses the *deployed* environment.json file **(from staging.openstax.org)** in the REX URI script to update cnx-deploy. **NOTE: _Is this list the correct? Has REX made any changes to it since staging deployment?_**
- [ ] CE enables feature flag for production deployment
- [ ] DevOps initiates deployment in below order:
        1. BIT
       2. REX
       3. CE

### Staging/Production Testing
- [ ] Cnx-automation tests:
    - https://github.com/openstax/cnx-automation/pull/576
    - https://github.com/openstax/cnx-automation/pull/574
    - https://github.com/openstax/cnx-automation/pull/605
- [ ] Manual tests using [REX/CNX Redirect Test Links](https://docs.google.com/spreadsheets/d/1RHYCEzyOXlAi0eFHBbiyj9Y7vN7_wkIXHRkTrcIy_mM/edit#gid=0)

**Comment by scb6** [comment]
deployed, closing.
