### ISSUE TITLE
Content Engineering Styles Deployment

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-deploy#1209]
Repos 
- [x] oer.exports v0.79.0 IMPORTANT: This requires that rhaptos.print egg be built and revved and deployed as well.
- [x] cnx-recipes v1-41-0
- [x] cnx-deploy v3.1.6

**Comment by scb6** [comment]
New tag containing updated `RhaptosPrint` and `oer.export` is v3.1.7
