### ISSUE TITLE
Refresh exercises-staging.openstax.org with data from production exercises.openstax.org

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-deploy#1218]
Context: #temp-rex-urls in Slack

**Comment by dtwilliamson** [comment]
This is so corrections made to production exercises are reflected in staging data and thus available for testing.

This will need to be signed off on by @carlycurran (including the timing of when it's done).

**Comment by carlycurran** [comment]
This is great with me. Can we do this on Thursday, after this week's release?

**Comment by scb6** [comment]
R2 complete.

**Comment by DarkPrinceFrost** [comment]
8 points
