### ISSUE TITLE
Legacy Retirement Banner

### ISSUE THREAD

**Issue by Bkblodget** [openstax/cnx-deploy#1251]
## Summary

We need a banner with the following messaging to appear on all pages of legacy.cnx.org effective on 2/7/2020.

"We’re retiring our Legacy Authoring Platform on June 30, 2020. Learn more [hyperlink to blog post]."

link to blog post: TBD

_**Note:** The hyperlink to the blog post may not be available to us until the morning of 2/7/2020. If that is the case, @brittweinstein will update this card with the link._ 

## Environment

legacy.cnx.org (all pages)

**Comment by brittweinstein** [comment]
@dtwilliamson here is the blog URL: https://openstax.org/blog/saying-goodbye-cnx
