### ISSUE TITLE
CNX retirement banner

### ISSUE THREAD

**Issue by Bkblodget** [openstax/cnx-deploy#1252]
## Summary

We need a banner with the following messaging to appear on all pages of cnx.org effective on 2/7/2020.

"CNX is retiring! Community-created content will remain viewable for two years, and then be moved to Internet Archive. Learn more [hyperlink to blog post]."

link to blog post: TBD

_**Note:** The hyperlink to the blog post may not be available to us until the morning of 2/7/2020. If that is the case, @brittweinstein will update this card with the link._ 

## Environment

cnx.org (all pages)

**Comment by brittweinstein** [comment]
@dtwilliamson here is the blog URL: https://openstax.org/blog/saying-goodbye-cnx
