### ISSUE TITLE
Set up basic authentication on legacy (account creation)

### ISSUE THREAD

**Issue by Bkblodget** [openstax/cnx-deploy#1259]
## Summary
 We are disabling external new account creation by removing the "get an account button" on legacy.cnx.org. **Internal** account creation is still needed. The account creation page - https://legacy.cnx.org/new_account - should still be accessible by internal users by way of basic authentication. 

**New account creation will be disabled on 3/1/2020. We would like the basic auth to be set up by the end of Q2**

Link to card on CE board: https://app.zenhub.com/workspaces/content-engineering-tech-team-5af1f4cc12da5e6d74331b60/issues/openstax/cnx/852

## Environment

This will only be effective for production legacy (legacy.cnx.org). Content servers should not receive this change.

**Comment by brittweinstein** [comment]
@scb6 I unhid this issue b/c this is work that the DevOps team will do. We've discussed this with Dennis in our weekly meeting. Is this the right place for this issue?

**Comment by scb6** [comment]
Yes. I will catch up with Dennis and get back to you if I need to.

**Comment by dtwilliamson** [comment]
"Request a Account" - lol

**Comment by Bkblodget** [comment]
I am closing this card because we removed the links on all legacy pages to create a new account. Users of CNX do not seem to know about the workaround of going directly to the URL https://legacy.cnx.org/new_account to create an account. Because of this, we are comfortable with eliminating this work and focusing on blocking log-in to legacy for all non-openstax users in June. 

card for blocking legacy login: https://app.zenhub.com/workspaces/content-engineering-tech-team-5af1f4cc12da5e6d74331b60/issues/openstax/cnx/955
