### ISSUE TITLE
Update retirement banner on legacy.cnx.org

### ISSUE THREAD

**Issue by Bkblodget** [openstax/cnx-deploy#1260]
## Summary

Please implement the below updates to the retirement banner on legacy.cnx.org:

**Wording:** "We’re retiring our Legacy Authoring Platform on June 30, 2020. Learn more [hyperlink to blog post: https://openstax.org/blog/saying-goodbye-cnx]."

**Coloring:** Orange background (#DF571E) with white text. Text Align center; Full width.

_note: banner wording on the below image is incorrect_
![Screen Shot 2020-02-18 at 3.42.07 PM.png](https://images.zenhubusercontent.com/5b572db8a74e9a33056ecb3c/4ef95bd9-9238-4705-b725-86a735b78fd9)

Original request card: https://app.zenhub.com/workspaces/devops-5c8a585ee5eb2f060be04613/issues/openstax/cnx-deploy/1251

## Environment

Legacy.cnx.org

**Comment by dtwilliamson** [comment]
I would recommend black text for an orange background. White on orange has poor contrast.

**Comment by dtwilliamson** [comment]
Production (and staging) banners have been restyled (white on #DF571E) and the wording corrected.
￼
