### ISSUE TITLE
Old Postgres pgdg apt source file needs to be removed

### ISSUE THREAD

**Issue by dtwilliamson** [openstax/cnx-deploy#1444]
## Summary

`"Failed to update apt cache: W:The repository 'http://apt.postgresql.org/pub/repos/apt precise-pgdg Release' does not have a Release file.`

The content of `/etc/apt/sources.list.d/pgdg.list` is

```deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.3```

But we're using Ubuntu Xenial and Postgres 9.4 (there's a sources file for `xenial-pgdg` which is maintained by Ansible)

The old sources file needs to be removed.

**Comment by m1yag1** [comment]
This is actually done already, closing ...
