### ISSUE TITLE
Cannot add module to collection on legacy-tea

### ISSUE THREAD

**Issue by edwoodward** [openstax/cnx-deploy#228]
## Summary

This was reported by Britney Blodget via Internal Support

CM team is getting a 500 error when adding a module to a collection on legacy-tea. I am able to add the same module to a new collection or a derived copy of the collection.

>http://legacy-tea.cnx.org/Members/manager1/col10007/subcollection.2017-01-10.6543681212/@@collection-composer-collection-module Failed to load resource: the server responded with a status of 500 (Internal Server Error)

The collection is col10007 and the module that is being added is m57395

## Environment

legacy-tex.cnx.org

**Comment by pumazi** [comment]
```pytb
Traceback (innermost last):
  Module ZPublisher.Publish, line 115, in publish
  Module ZPublisher.mapply, line 88, in mapply
  Module ZPublisher.Publish, line 41, in call_object
  Module Products.RhaptosCollection.browser.ajaxcomposer.collection_module, line 34, in __call__
  Module Products.CMFCore.FSPythonScript, line 108, in __call__
  Module Shared.DC.Scripts.Bindings, line 311, in __call__
  Module Products.PloneHotfix20110531, line 106, in _patched_bindAndExec
  Module Products.PloneHotfix20130618.spamProtect, line 35, in _patched_bindAndExec
  Module Products.PloneHotfix20121106.python_scripts, line 63, in _patched_bindAndExec
  Module Shared.DC.Scripts.Bindings, line 348, in _bindAndExec
  Module Products.CMFCore.FSPythonScript, line 164, in _exec
  Module None, line 10, in addModulesToCourse
   - <FSPythonScript at /plone/addModulesToCourse used for /plone/Members/manager1/col10007/subcollection.2017-01-10.6543681212>
   - Line 10
  Module Products.RhaptosCollection.types.CollectionBase, line 68, in containedModuleIds
  Module Products.RhaptosCollection.types.ContentPointer, line 68, in getModuleId
AttributeError: 'NoneType' object has no attribute 'getId'```

**Comment by reedstrm** [comment]
I think this has to do with the module zodb stub objects not existing until they've been visited  - the way that code is fetching it is not triggering the 'create a zodb object' that url fetching is.

**Comment by pumazi** [comment]
@reedstrm Could you document the solution you did on this issue in case of future occurrences. Thanks 😸

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
