### ISSUE TITLE
zclient instance logs need x-forwaded-for

### ISSUE THREAD

**Issue by dtwilliamson** [openstax/cnx-deploy#247]
## Summary

The zclient instance logs (and others?) need X-FORWADED-FOR to show the original IP address of the requestor. Otherwise we only see the IP address of the proxy.

## Environment

I verified this issue on dev01 and 02 and staging04 and 05.

**Comment by pumazi** [comment]
Could this also be happening on prod? Seems like HaProxy would be the culprit and it's currently in the prod infrastructure.

**Comment by dtwilliamson** [comment]
Yes. I just checked fountain and it's only showing connections from prod03 and butter.

**Comment by DarkPrinceFrost** [comment]
I may be wrong, but I'm thinking that the IP address in the instance logs isn't coming from the request headers. I believe it's using the IP address of the connected socket.

**Comment by reedstrm** [comment]
We're not keeping access logs at haproxy, I guess?

**Comment by DarkPrinceFrost** [comment]
We have the logs in varnish @reedstrm

**Comment by DarkPrinceFrost** [comment]
I confirmed that the logging facility was using the socket address as the client regardless of `X-Forwarded-For`

Only method that worked was patching 
`/var/lib/cnx/cnx-buildout/parts/zope2/lib/python/ZServer/medusa/http_server.py`
```patch
@@ -274,6 +274,8 @@
         if not user_agent: user_agent=''
         referer=self.get_header('referer')
         if not referer: referer=''  
+        forward=self.get_header('x-forwarded-for')
+        if not forward: forward='-'
        
         auth=self.get_header('Authorization')
         name='Anonymous'
@@ -289,7 +291,8 @@
 
         self.channel.server.logger.log (
             self.channel.addr[0],
-            '- %s [%s] "%s" %d %d "%s" "%s"\n' % (
+            '- (%s) %s [%s] "%s" %d %d "%s" "%s"\n' % (
+                forward,
                 name,
                 self.log_date_string (time.time()),
                 self.request,
```

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
