### ISSUE TITLE
Institute hashes for advanced package acquisition security

### ISSUE THREAD

**Issue by pumazi** [openstax/cnx-deploy#263]
## Summary

We should add the file hashes to our requirements.txt to ensure third-party package downloads are the exact same as those we anticipate obtaining. See also https://pip.pypa.io/en/stable/reference/pip_hash/ for how to get the hash.

## Environment

all

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
