### ISSUE TITLE
need a db pool

### ISSUE THREAD

**Issue by reedstrm** [openstax/cnx-deploy#315]
## Summary

Occasionally, if too many log-running queries (like searches) get through to the DB, we get an exponential slowdown

## Environment
Production

## Action
Proposed fix - deploy a connection pooler (pgbouncer and pg_pool II seem to be the two likliest candidates) to limit the number of active connections allowed to the DB. It has been shown that this actually improves average latency of queries for postgresql (over allowing hundreds of connections to the db).

**Comment by karenc** [comment]
We had lots of idle postgres connections on production which should be fixed in https://github.com/Connexions/cnx-archive/pull/528 and https://github.com/Connexions/cnx-publishing/pull/187.

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
