### ISSUE TITLE
Need a route for rabbitmq management plugin access

### ISSUE THREAD

**Issue by reedstrm** [openstax/cnx-deploy#362]
## Summary

Current deployments (properly) lock down most ports on the servers. We're now beginning to deploy rabbitmq, which comes with a useful management plugin service on port 15672. Devs and QA need a way to reach this interface on dev and QA machines, Operations (and perhaps QA) will need access to this for production. Currently, I have been using ssh local tunnels to access this (i.e. `ssh -L 15673:localhost:15672 server_of_interest`) This is probably acceptable for devs, but is marginal for QA, and not at all correct for production. Rather than opening the port, we need to provide another path or hostname that is rewritten and proxied to that server.

We may want to consider using the LDAP integration, since there is need to control access and what can be done from these interfaces: https://www.rabbitmq.com/ldap.html

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
