### ISSUE TITLE
Unable to use psql 9.4 on fresh ubuntu 16.04 servers

### ISSUE THREAD

**Issue by karenc** [openstax/cnx-deploy#433]
## Summary

On a fresh Ubuntu 16.04 server:

```
karen@xenial-openstax-test:~$ psql -U cnxarchive cnxarchive
Error: Invalid data directory
```

psql is a perl script in postgresql-common package:

```
karen@xenial-openstax-test:~$ which psql
/usr/bin/psql
karen@xenial-openstax-test:~$ file /usr/bin/psql
/usr/bin/psql: symbolic link to ../share/postgresql-common/pg_wrapper
```

By comparing the different versions of postgresql-common, it seems the new version of `psql` sets the cluster to `main` if `PGCLUSTER` or `PGHOST` is not set.  So by setting `PGHOST`:

```
karen@xenial-openstax-test:~$ PGHOST=localhost psql -U cnxarchive cnxarchive
psql (9.4.15)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

cnxarchive=>
```

The other way is to use the postgres user:

```
karen@xenial-openstax-test:~$ sudo -u postgres psql -U cnxarchive cnxarchive
psql (9.4.15)
Type "help" for help.

cnxarchive=>
```

The other way is to use the specific version of psql:

```
karen@xenial-openstax-test:~$ /usr/lib/postgresql/9.4/bin/psql -U cnxarchive cnxarchive
psql (9.4.15)
Type "help" for help.

cnxarchive=>
```

In #423 we used `PGHOST` but we are looking at other ways of fixing this, so opening this issue.

## Environment

all on ubuntu 16.04

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
