### ISSUE TITLE
create special accounts when dev and staging deploy or data sync

### ISSUE THREAD

**Issue by kerwinso** [openstax/cnx-deploy#496]
## Summary
When a new dev-class machine is deployed, it would be good to run the
cnx-buildout/scripts/add_users.sh script, to have available the user1,2,3 manager1, etc.

In addition, when staging has a data-refresh from production (including the ZODB)
we need to recreate special tester accounts (specifically, for contract testers). For that,
we'll probably need to vault some user/password pairs, and feed them to:
cnx-buildout/scripts/addRhaptosUser.zctl script

**Comment by dtwilliamson** [comment]
@kerwinso I'll create these accounts. Normally this would be a Slack request. It's not done during deployment.

**Comment by kerwinso** [comment]
Trello card: https://trello.com/c/1QUUd5DP

**Comment by pumazi** [comment]
Seems like this should remain an on request type of thing. 😕

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
