### ISSUE TITLE
Prevent indexing of certain pages in robots.txt

### ISSUE THREAD

**Issue by brittany-johnson** [openstax/cnx-deploy#925]
@edwoodward commented on [Thu Nov 15 2018](https://github.com/Connexions/webview/issues/2067)

Google sent an alert that an admin page had a display issue on mobile. Google should not be indexing any pages that are under cnx.org/a/. We need to prevent this by adding a disallow in robots.txt.  

This should also disallow the haproxy-status page as well

URL from Google Alert
>https://cnx.org/a/print-style/ccap-developmental-math
>https://cnx.org/haproxy-status

**Acceptance Criteria**

robots.txt file on server should contain...
>Disallow: /a/
>Disallow: /haproxy-status

**Comment by openstaxalina** [comment]
@brittany-johnson is going to check with Ed what remains to be done here, and if she makes a PR, what is merge process for cnx-deploy.

**Comment by brittany-johnson** [comment]
@omehes Ready for testing!

**Comment by brittany-johnson** [comment]
Update: Due to the fact that all servers except production disallow everything, this fix will have to be tested on production.

**Comment by omehes** [comment]
@brittany-johnson how can I test this? can you add some steps/instructions pls.

**Comment by brittweinstein** [comment]
@edwoodward could you provide testing steps, please?

**Comment by omehes** [comment]
Verified on cnx.org

{"date": "2019-01-29 09:38:51 CST",
 "webview": "65e33ad4775417bd5dfcb698d5cab69f1d594466 (v0.44.0)",
 "cnx-archive": "4.8.0",
 "cnx-publishing": "0.15.0",
 "oer.exports": "zen.zombie v0.70.0",
 "press": "8.0.1",
 "cnx-deploy": "v2.35.0"
}

Sitemap: https://cnx.org/sitemap_index.xml
User-agent: ScoutJet
Crawl-delay: 10
Disallow: legacy.cnx.org
Disallow: /lenses
Disallow: /browse_content
Disallow: /*/pdf$
Disallow: /*/epub$
Disallow: /*/complete$
Disallow: /*/offline$
Disallow: /*?format=*$
Disallow: /*/multimedia$
Disallow: /*/lens_add?*$
Disallow: /lens_add
Disallow: /*/lens_view/*$
Disallow: /content/*view_mode=statistics$
Disallow: /a/
Disallow: /haproxy-status

User-agent: *
Disallow: legacy.cnx.org
Disallow: /lenses
Disallow: /browse_content
Disallow: /*/pdf$
Disallow: /*/epub$
Disallow: /*/complete$
Disallow: /*/offline$
Disallow: /*?format=*$
Disallow: /*/multimedia$
Disallow: /*/lens_add?*$
Disallow: /lens_add
Disallow: /*/lens_view/*$
Disallow: /content/*view_mode=statistics$
Disallow: /a/
Disallow: /haproxy-status

User-agent: Baiduspider
Crawl-delay: 10
Disallow: legacy.cnx.org
Disallow: /lenses
Disallow: /browse_content
Disallow: /*/pdf$
Disallow: /*/epub$
Disallow: /*/complete$
Disallow: /*/offline$
Disallow: /*?format=*$
Disallow: /*/multimedia$
Disallow: /*/lens_add?*$
Disallow: /lens_add
Disallow: /*/lens_view/*$
Disallow: /content/*view_mode=statistics$
Disallow: /a/
Disallow: /haproxy-status

User-agent: BecomeBot
Crawl-delay: 20
Disallow: legacy.cnx.org
Disallow: /lenses
Disallow: /browse_content
Disallow: /*/pdf$
Disallow: /*/epub$
Disallow: /*/complete$
Disallow: /*/offline$
Disallow: /*?format=*$
Disallow: /*/multimedia$
Disallow: /*/lens_add?*$
Disallow: /lens_add
Disallow: /*/lens_view/*$
Disallow: /content/*view_mode=statistics$
Disallow: /a/
Disallow: /haproxy-status

User-agent: Slurp
Crawl-delay: 10
Disallow: legacy.cnx.org
Disallow: /lenses
Disallow: /browse_content
Disallow: /*/pdf$
Disallow: /*/epub$
Disallow: /*/complete$
Disallow: /*/offline$
Disallow: /*?format=*$
Disallow: /*/multimedia$
Disallow: /*/lens_add?*$
Disallow: /lens_add
Disallow: /*/lens_view/*$
Disallow: /content/*view_mode=statistics$
Disallow: /a/
Disallow: /haproxy-status
