### ISSUE TITLE
Maybe use haproxy module for HAProxy configuration?

### ISSUE THREAD

**Issue by pumazi** [openstax/cnx-deploy#93]
## Summary

Maybe we should use the [haproxy module](https://docs.ansible.com/ansible/haproxy_module.html)?
At the moment this seems like a bad idea,
because if we change the `zclient_count` we don't have a real easy way
to disable the dead nodes. One way around this would be to store
the previous host specific `zclient_count` value next to the haproxy
configuration. Then if the number exceeds the current count, disable the
exceeded range.

In the mean time, the simple and consistent solution is to use a templated
configuration file.
## Environment

all

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
